/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProfessorJFrame;

import java.awt.Cursor;
import MainLoginJFrame.MainLoginFrame;
import javax.swing.ImageIcon;
import Professor.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DongHyeon Kim <20183188>
 */
public class ProfessorFrame extends javax.swing.JFrame {
    
    DefaultTableModel LectureTableModel;
    DefaultTableModel StudentTableModel;
    DefaultTableModel GradeTableModel;
    DefaultTableModel SetGradeTableModel;
    DefaultTableModel LecTableToATDModel;
    DefaultTableModel AttendanceTableModel;
    
    int mouseX;
    int mouseY;
    String userID;
    String NowSelectedLecture = " ";
    /**
     * Creates new form ProfessorFrame
     */
    public ProfessorFrame() {
        initComponents();
        VIEWSTUDENTPanel.setVisible(true);
        SETGRADEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setVisible(false);
        STUDENTLISTPanel.setVisible(false);
        SETGRADE2panel.setVisible(false);
        ATTENDANCEPanel.setVisible(false);
        PASSWORDPanel.setVisible(false);
        
        VIEWSTUDENTPanel.setEnabled(true);
        SETGRADEPanel.setEnabled(false);
        VIEWATTENDANCEPanel.setEnabled(false);
        STUDENTLISTPanel.setEnabled(false);
        SETGRADE2panel.setEnabled(false);
        ATTENDANCEPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(false);
        
        ATTENDANCEPanel.setVisible(false);
        ATTENDANCEPanel.setEnabled(false);
        
        LectureTableModel = (DefaultTableModel) LectureTable.getModel();
        StudentTableModel = (DefaultTableModel) StudentTable.getModel();
        GradeTableModel = (DefaultTableModel) GradeTable.getModel();
        SetGradeTableModel = (DefaultTableModel) SetGradeTable.getModel();
        LecTableToATDModel = (DefaultTableModel) LecTableToATD.getModel();
        AttendanceTableModel = (DefaultTableModel) AttendanceTable.getModel();
        
        StudentNumField.setBackground(new Color(0, 0, 0, 1));
        StudentNameField.setBackground(new Color(0, 0, 0, 1));
        StudentMajorField.setBackground(new Color(0, 0, 0, 1));
        NowPW.setBackground(new Color(0, 0, 0, 1));
        AfterPW.setBackground(new Color(0, 0, 0, 1));
        NowUser.setText(userID);
        NowUser.setForeground(Color.white);
        
        CheckStudentList c = new CheckStudentList();
        c.ViewProfessorLecture(userID, LectureTableModel);
    }
    
    public ProfessorFrame(String userID) {
        initComponents();
        VIEWSTUDENTPanel.setVisible(true);
        SETGRADEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setVisible(false);
        STUDENTLISTPanel.setVisible(false);
        SETGRADE2panel.setVisible(false);
        ATTENDANCEPanel.setVisible(false);
        PASSWORDPanel.setVisible(false);
        
        VIEWSTUDENTPanel.setEnabled(true);
        SETGRADEPanel.setEnabled(false);
        VIEWATTENDANCEPanel.setEnabled(false);
        STUDENTLISTPanel.setEnabled(false);
        SETGRADE2panel.setEnabled(false);
        ATTENDANCEPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(false);
        
        LectureTableModel = (DefaultTableModel) LectureTable.getModel();
        StudentTableModel = (DefaultTableModel) StudentTable.getModel();
        GradeTableModel = (DefaultTableModel) GradeTable.getModel();
        SetGradeTableModel = (DefaultTableModel) SetGradeTable.getModel();
        LecTableToATDModel = (DefaultTableModel) LecTableToATD.getModel();
        AttendanceTableModel = (DefaultTableModel) AttendanceTable.getModel();
        
        StudentNumField.setBackground(new Color(0, 0, 0, 1));
        StudentNameField.setBackground(new Color(0, 0, 0, 1));
        StudentMajorField.setBackground(new Color(0, 0, 0, 1));
        NowPW.setBackground(new Color(0, 0, 0, 1));
        AfterPW.setBackground(new Color(0, 0, 0, 1));
        
        this.userID = userID;
        NowUser.setText(userID);
        NowUser.setForeground(Color.white);
        
        CheckStudentList c = new CheckStudentList();
        c.ViewProfessorLecture(userID, LectureTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        SETGRADE2panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SetGradeTable = new javax.swing.JTable();
        VIEWLectureList1 = new javax.swing.JButton();
        StudentMajorField = new javax.swing.JTextField();
        StudentNameField = new javax.swing.JTextField();
        StudentNumField = new javax.swing.JTextField();
        StudentNumBG = new javax.swing.JLabel();
        StudentNumText = new javax.swing.JLabel();
        NameBG = new javax.swing.JLabel();
        NameText = new javax.swing.JLabel();
        MajorBG = new javax.swing.JLabel();
        MajorText = new javax.swing.JLabel();
        GradeComboBox = new javax.swing.JComboBox<>();
        GradeText = new javax.swing.JLabel();
        InputGrade = new javax.swing.JButton();
        LectureInfo = new javax.swing.JLabel();
        LecNum = new javax.swing.JLabel();
        SetGradeText2 = new javax.swing.JLabel();
        SETGRADEPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GradeTable = new javax.swing.JTable();
        SelectLectureGrade = new javax.swing.JButton();
        SetGradeText = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PASSWORDPanel = new javax.swing.JPanel();
        NowPW = new javax.swing.JTextField();
        AfterPW = new javax.swing.JPasswordField();
        ChangePassword = new javax.swing.JLabel();
        NowPasswordText = new javax.swing.JLabel();
        NowPasswordField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChagePasswordField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ATTENDANCEPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        AttendanceTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        LecNumText = new javax.swing.JLabel();
        LecInfoText = new javax.swing.JLabel();
        BackButt = new javax.swing.JButton();
        VIEWSTUDENTPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LectureTable = new javax.swing.JTable();
        SelectLecture = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VIEWATTENDANCEPanel = new javax.swing.JPanel();
        LecTable1 = new javax.swing.JScrollPane();
        LecTableToATD = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        SelectLecture1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        STUDENTLISTPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        STUDENTLISTtext = new javax.swing.JLabel();
        VIEWLectureList = new javax.swing.JButton();
        BasePanel = new javax.swing.JPanel();
        ChangePW = new javax.swing.JLabel();
        NowUser = new javax.swing.JLabel();
        SETGRADE = new javax.swing.JLabel();
        VIEWATTENDANCE = new javax.swing.JLabel();
        VIEWSTUDENT = new javax.swing.JLabel();
        LogoutButt = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        DragBar = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SETGRADE2panel.setBackground(new java.awt.Color(250, 250, 250));
        SETGRADE2panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SetGradeTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        SetGradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "학번", "이름", "학과", "성적"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SetGradeTable.setRowHeight(25);
        SetGradeTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        SetGradeTable.setShowVerticalLines(false);
        SetGradeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetGradeTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(SetGradeTable);
        if (SetGradeTable.getColumnModel().getColumnCount() > 0) {
            SetGradeTable.getColumnModel().getColumn(0).setResizable(false);
            SetGradeTable.getColumnModel().getColumn(1).setResizable(false);
            SetGradeTable.getColumnModel().getColumn(2).setResizable(false);
            SetGradeTable.getColumnModel().getColumn(3).setResizable(false);
        }

        SETGRADE2panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 220));

        VIEWLectureList1.setText("강의 목록 보기");
        VIEWLectureList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VIEWLectureList1MouseClicked(evt);
            }
        });
        SETGRADE2panel.add(VIEWLectureList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 130, 40));

        StudentMajorField.setEditable(false);
        StudentMajorField.setBorder(null);
        SETGRADE2panel.add(StudentMajorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 150, 40));

        StudentNameField.setEditable(false);
        StudentNameField.setBorder(null);
        SETGRADE2panel.add(StudentNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, 40));

        StudentNumField.setEditable(false);
        StudentNumField.setBorder(null);
        SETGRADE2panel.add(StudentNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 80, 40));

        StudentNumBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/MiddleInputField.png"))); // NOI18N
        SETGRADE2panel.add(StudentNumBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        StudentNumText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        StudentNumText.setText("학번");
        SETGRADE2panel.add(StudentNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        NameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        SETGRADE2panel.add(NameBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        NameText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        NameText.setText("이름");
        SETGRADE2panel.add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        MajorBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        SETGRADE2panel.add(MajorBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        MajorText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MajorText.setText("학과");
        SETGRADE2panel.add(MajorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        GradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "F" }));
        SETGRADE2panel.add(GradeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 110, 30));

        GradeText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GradeText.setText("성적");
        SETGRADE2panel.add(GradeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        InputGrade.setText("성적 입력");
        InputGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputGradeMouseClicked(evt);
            }
        });
        SETGRADE2panel.add(InputGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 130, 40));

        LectureInfo.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        SETGRADE2panel.add(LectureInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 420, 20));

        LecNum.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        SETGRADE2panel.add(LecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 20));

        SetGradeText2.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        SetGradeText2.setText("SET GRADE");
        SETGRADE2panel.add(SetGradeText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(SETGRADE2panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        SETGRADEPanel.setBackground(new java.awt.Color(250, 250, 250));
        SETGRADEPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GradeTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "강의 번호", "강의명", "담당 학과", "학점", "담당 교수"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GradeTable.setRowHeight(25);
        GradeTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        GradeTable.setShowVerticalLines(false);
        GradeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradeTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(GradeTable);
        if (GradeTable.getColumnModel().getColumnCount() > 0) {
            GradeTable.getColumnModel().getColumn(0).setResizable(false);
            GradeTable.getColumnModel().getColumn(1).setResizable(false);
            GradeTable.getColumnModel().getColumn(2).setResizable(false);
            GradeTable.getColumnModel().getColumn(3).setResizable(false);
            GradeTable.getColumnModel().getColumn(4).setResizable(false);
        }

        SETGRADEPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 260));

        SelectLectureGrade.setText("강의 선택");
        SelectLectureGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectLectureGradeMouseClicked(evt);
            }
        });
        SETGRADEPanel.add(SelectLectureGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 140, 40));

        SetGradeText.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        SetGradeText.setText("SET GRADE");
        SETGRADEPanel.add(SetGradeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel6.setText("* 강의를 선택하면 성적 입력이 가능합니다.");
        SETGRADEPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 590, -1));

        getContentPane().add(SETGRADEPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        PASSWORDPanel.setBackground(new java.awt.Color(250, 250, 250));
        PASSWORDPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NowPW.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        NowPW.setBorder(null);
        PASSWORDPanel.add(NowPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 150, 30));

        AfterPW.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        AfterPW.setBorder(null);
        PASSWORDPanel.add(AfterPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 30));

        ChangePassword.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        ChangePassword.setText("CHANGE PASSWORD");
        PASSWORDPanel.add(ChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 240, 50));

        NowPasswordText.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        NowPasswordText.setText("현재 비밀번호          :   ");
        PASSWORDPanel.add(NowPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        NowPasswordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        PASSWORDPanel.add(NowPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 30));

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel8.setText("변경할 비밀번호       : ");
        PASSWORDPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, -1));

        ChagePasswordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        PASSWORDPanel.add(ChagePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        jButton1.setText("비밀번호 변경");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PASSWORDPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 130, 40));

        getContentPane().add(PASSWORDPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        ATTENDANCEPanel.setBackground(new java.awt.Color(250, 250, 250));
        ATTENDANCEPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AttendanceTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        AttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "학번", "이름", "학과", "성적"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AttendanceTable.setRowHeight(25);
        AttendanceTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        AttendanceTable.setShowVerticalLines(false);
        AttendanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttendanceTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(AttendanceTable);
        if (AttendanceTable.getColumnModel().getColumnCount() > 0) {
            AttendanceTable.getColumnModel().getColumn(0).setResizable(false);
            AttendanceTable.getColumnModel().getColumn(1).setResizable(false);
            AttendanceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        ATTENDANCEPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 590, 220));

        jLabel3.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel3.setText("ATTENDANCE");
        ATTENDANCEPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 62, 158, 34));

        LecNumText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ATTENDANCEPanel.add(LecNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 106, 89, 18));

        LecInfoText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ATTENDANCEPanel.add(LecInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 106, 439, 18));

        BackButt.setText("강의 목록 보기");
        BackButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtMouseClicked(evt);
            }
        });
        ATTENDANCEPanel.add(BackButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 130, 40));

        getContentPane().add(ATTENDANCEPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        VIEWSTUDENTPanel.setBackground(new java.awt.Color(250, 250, 250));
        VIEWSTUDENTPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LectureTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LectureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "강의 번호", "강의명", "담당 학과", "학점", "담당 교수"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LectureTable.setRowHeight(25);
        LectureTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        LectureTable.setShowVerticalLines(false);
        LectureTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LectureTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LectureTable);
        if (LectureTable.getColumnModel().getColumnCount() > 0) {
            LectureTable.getColumnModel().getColumn(0).setResizable(false);
            LectureTable.getColumnModel().getColumn(1).setResizable(false);
            LectureTable.getColumnModel().getColumn(2).setResizable(false);
            LectureTable.getColumnModel().getColumn(3).setResizable(false);
            LectureTable.getColumnModel().getColumn(4).setResizable(false);
        }

        VIEWSTUDENTPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 260));

        SelectLecture.setText("강의 선택");
        SelectLecture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectLectureMouseClicked(evt);
            }
        });
        VIEWSTUDENTPanel.add(SelectLecture, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 136, 43));

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel1.setText("PROFESSOR LECTURE LIST");
        VIEWSTUDENTPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 40));

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel5.setText("* 강의를 선택하면 학생 명단 조회가 가능합니다.");
        VIEWSTUDENTPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 550, -1));

        getContentPane().add(VIEWSTUDENTPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        VIEWATTENDANCEPanel.setBackground(new java.awt.Color(250, 250, 250));
        VIEWATTENDANCEPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LecTableToATD.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LecTableToATD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "강의 번호", "강의명", "담당 학과", "학점", "담당 교수"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LecTableToATD.setRowHeight(25);
        LecTableToATD.setSelectionBackground(new java.awt.Color(0, 204, 255));
        LecTableToATD.setShowVerticalLines(false);
        LecTableToATD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LecTableToATDMouseClicked(evt);
            }
        });
        LecTable1.setViewportView(LecTableToATD);
        if (LecTableToATD.getColumnModel().getColumnCount() > 0) {
            LecTableToATD.getColumnModel().getColumn(0).setResizable(false);
            LecTableToATD.getColumnModel().getColumn(1).setResizable(false);
            LecTableToATD.getColumnModel().getColumn(2).setResizable(false);
            LecTableToATD.getColumnModel().getColumn(3).setResizable(false);
            LecTableToATD.getColumnModel().getColumn(4).setResizable(false);
        }

        VIEWATTENDANCEPanel.add(LecTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 260));

        jLabel2.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel2.setText("PROFESSOR LECTURE LIST");
        VIEWATTENDANCEPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 40));

        SelectLecture1.setText("강의 선택");
        SelectLecture1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectLecture1MouseClicked(evt);
            }
        });
        VIEWATTENDANCEPanel.add(SelectLecture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 136, 43));

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel4.setText("* 강의를 선택하면 출석부 조회가 가능합니다.");
        VIEWATTENDANCEPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 590, -1));

        getContentPane().add(VIEWATTENDANCEPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        STUDENTLISTPanel.setBackground(new java.awt.Color(250, 250, 250));
        STUDENTLISTPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StudentTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "학번", "이름", "학과"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.setRowHeight(25);
        StudentTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        StudentTable.setShowVerticalLines(false);
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StudentTable);
        if (StudentTable.getColumnModel().getColumnCount() > 0) {
            StudentTable.getColumnModel().getColumn(0).setResizable(false);
            StudentTable.getColumnModel().getColumn(1).setResizable(false);
            StudentTable.getColumnModel().getColumn(2).setResizable(false);
        }

        STUDENTLISTPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 260));

        STUDENTLISTtext.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        STUDENTLISTtext.setText("STUDENT LIST");
        STUDENTLISTPanel.add(STUDENTLISTtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 40));

        VIEWLectureList.setText("강의 목록 보기");
        VIEWLectureList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VIEWLectureListMouseClicked(evt);
            }
        });
        STUDENTLISTPanel.add(VIEWLectureList, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 130, 40));

        getContentPane().add(STUDENTLISTPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        BasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangePW.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ChangePW.setForeground(new java.awt.Color(255, 255, 255));
        ChangePW.setText("비밀번호 변경");
        ChangePW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePWMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePWMouseExited(evt);
            }
        });
        BasePanel.add(ChangePW, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 20));
        BasePanel.add(NowUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, 20));

        SETGRADE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/SET GRADE.png"))); // NOI18N
        SETGRADE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETGRADEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETGRADEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETGRADEMouseExited(evt);
            }
        });
        BasePanel.add(SETGRADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 50));

        VIEWATTENDANCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/VIEW ATTENDANCE.png"))); // NOI18N
        VIEWATTENDANCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VIEWATTENDANCEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VIEWATTENDANCEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VIEWATTENDANCEMouseExited(evt);
            }
        });
        BasePanel.add(VIEWATTENDANCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        VIEWSTUDENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/VIEW STUDENT.png"))); // NOI18N
        VIEWSTUDENT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VIEWSTUDENTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VIEWSTUDENTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VIEWSTUDENTMouseExited(evt);
            }
        });
        BasePanel.add(VIEWSTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        LogoutButt.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        LogoutButt.setText(" LOGOUT");
        LogoutButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtMouseExited(evt);
            }
        });
        BasePanel.add(LogoutButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 60, 20));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/exitmini.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        BasePanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 30, 30));

        DragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragBarMouseDragged(evt);
            }
        });
        DragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragBarMousePressed(evt);
            }
        });
        BasePanel.add(DragBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/BaseBackGround.png"))); // NOI18N
        BasePanel.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        getContentPane().add(BasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_DragBarMouseDragged

    private void DragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragBarMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();

    }//GEN-LAST:event_DragBarMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_ExitMouseExited

    private void LogoutButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MainLoginFrame l = new MainLoginFrame();
        l.setVisible(true);
    }//GEN-LAST:event_LogoutButtMouseClicked

    private void LogoutButtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseEntered
        // TODO add your handling code here:
        this.setCursor(HAND_CURSOR);
    }//GEN-LAST:event_LogoutButtMouseEntered

    private void LogoutButtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseExited
        // TODO add your handling code here:
        this.setCursor(0);
    }//GEN-LAST:event_LogoutButtMouseExited

    private void VIEWSTUDENTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWSTUDENTMouseEntered
        // TODO add your handling code here:
        VIEWSTUDENT.setIcon(new ImageIcon("./src/ProfessorJFrame/VIEW STUDENT Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_VIEWSTUDENTMouseEntered

    private void VIEWSTUDENTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWSTUDENTMouseExited
        // TODO add your handling code here:
        VIEWSTUDENT.setIcon(new ImageIcon("./src/ProfessorJFrame/VIEW STUDENT.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_VIEWSTUDENTMouseExited

    private void SETGRADEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETGRADEMouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        
        VIEWSTUDENTPanel.setVisible(false);
        SETGRADEPanel.setVisible(true);
        VIEWATTENDANCEPanel.setVisible(false);
        STUDENTLISTPanel.setVisible(false);
        SETGRADE2panel.setVisible(false);
        
        VIEWSTUDENTPanel.setEnabled(false);
        SETGRADEPanel.setEnabled(true);
        VIEWATTENDANCEPanel.setEnabled(false);
        STUDENTLISTPanel.setEnabled(false);
        SETGRADE2panel.setEnabled(false);
        
        ATTENDANCEPanel.setVisible(false);
        ATTENDANCEPanel.setEnabled(false);
        
        PASSWORDPanel.setVisible(false);
        PASSWORDPanel.setEnabled(false);
        c.ViewProfessorLecture(userID, GradeTableModel);
    }//GEN-LAST:event_SETGRADEMouseClicked

    private void SETGRADEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETGRADEMouseEntered
        // TODO add your handling code here:
        SETGRADE.setIcon(new ImageIcon("./src/ProfessorJFrame/SET GRADE Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_SETGRADEMouseEntered

    private void SETGRADEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETGRADEMouseExited
        // TODO add your handling code here:
        SETGRADE.setIcon(new ImageIcon("./src/ProfessorJFrame/SET GRADE.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_SETGRADEMouseExited

    private void VIEWATTENDANCEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWATTENDANCEMouseEntered
        // TODO add your handling code here:
        VIEWATTENDANCE.setIcon(new ImageIcon("./src/ProfessorJFrame/VIEW ATTENDANCE Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_VIEWATTENDANCEMouseEntered

    private void VIEWATTENDANCEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWATTENDANCEMouseExited
        // TODO add your handling code here:
        VIEWATTENDANCE.setIcon(new ImageIcon("./src/ProfessorJFrame/VIEW ATTENDANCE.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_VIEWATTENDANCEMouseExited

    private void VIEWSTUDENTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWSTUDENTMouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        VIEWSTUDENTPanel.setVisible(true);
        SETGRADEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setVisible(false);
        STUDENTLISTPanel.setVisible(false);
        SETGRADE2panel.setVisible(false);
        
        VIEWSTUDENTPanel.setEnabled(true);
        SETGRADEPanel.setEnabled(false);
        VIEWATTENDANCEPanel.setEnabled(false);
        STUDENTLISTPanel.setEnabled(false);
        SETGRADE2panel.setVisible(false);
        
        ATTENDANCEPanel.setVisible(false);
        ATTENDANCEPanel.setEnabled(false);
        
        PASSWORDPanel.setVisible(false);
        PASSWORDPanel.setEnabled(false);
        c.ViewProfessorLecture(userID, LectureTableModel);
    }//GEN-LAST:event_VIEWSTUDENTMouseClicked

    private void VIEWATTENDANCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWATTENDANCEMouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        VIEWSTUDENTPanel.setVisible(false);
        SETGRADEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setVisible(true);
        STUDENTLISTPanel.setVisible(false);
        SETGRADE2panel.setVisible(false);
        
        VIEWSTUDENTPanel.setEnabled(false);
        SETGRADEPanel.setEnabled(false);
        VIEWATTENDANCEPanel.setEnabled(true);
        STUDENTLISTPanel.setEnabled(false);
        SETGRADE2panel.setEnabled(false);
        
        ATTENDANCEPanel.setVisible(false);
        ATTENDANCEPanel.setEnabled(false);
        
        PASSWORDPanel.setVisible(false);
        PASSWORDPanel.setEnabled(false);
        c.ViewProfessorLecture(userID, LecTableToATDModel);
    }//GEN-LAST:event_VIEWATTENDANCEMouseClicked

    private void LectureTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LectureTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = LectureTable.getSelectedRow();
        String CourseNum = (String) LectureTable.getValueAt(selectedRow, 0);
        String CourseName = (String) LectureTable.getValueAt(selectedRow, 1);
        String Major = (String) LectureTable.getValueAt(selectedRow, 2);
        String Credit = (String) LectureTable.getValueAt(selectedRow, 3);
        String Info = (String) LectureTable.getValueAt(selectedRow, 4);
    }//GEN-LAST:event_LectureTableMouseClicked

    private void SelectLectureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectLectureMouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        int selectedRow = LectureTable.getSelectedRow();
        String LectrueNum = (String) LectureTable.getValueAt(selectedRow, 0);
        
        VIEWSTUDENTPanel.setVisible(false);
        VIEWSTUDENTPanel.setEnabled(false);
        
        STUDENTLISTPanel.setVisible(true);
        STUDENTLISTPanel.setEnabled(true);
        
        c.ViewStudentList(LectrueNum, StudentTableModel);

    }//GEN-LAST:event_SelectLectureMouseClicked

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentTableMouseClicked

    private void VIEWLectureListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWLectureListMouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        VIEWSTUDENTPanel.setVisible(true);
        SETGRADEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setVisible(false);
        STUDENTLISTPanel.setVisible(false);
        
        VIEWSTUDENTPanel.setEnabled(true);
        SETGRADEPanel.setEnabled(false);
        VIEWATTENDANCEPanel.setEnabled(false);
        STUDENTLISTPanel.setEnabled(false);
        
        c.ViewProfessorLecture(userID, LectureTableModel);
    }//GEN-LAST:event_VIEWLectureListMouseClicked

    private void GradeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeTableMouseClicked

    private void SetGradeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetGradeTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = SetGradeTable.getSelectedRow();
        
        StudentNumField.setText((String) SetGradeTable.getValueAt(selectedRow, 0));
        StudentNameField.setText((String) SetGradeTable.getValueAt(selectedRow, 1));
        StudentMajorField.setText((String) SetGradeTable.getValueAt(selectedRow, 2));

    }//GEN-LAST:event_SetGradeTableMouseClicked

    private void SelectLectureGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectLectureGradeMouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        
        SETGRADEPanel.setVisible(false);
        SETGRADE2panel.setVisible(true);
        
        SETGRADEPanel.setEnabled(false);
        SETGRADE2panel.setEnabled(true);
        
        int selectedRow = GradeTable.getSelectedRow();
        String LectureNum = (String) GradeTable.getValueAt(selectedRow, 0);
        NowSelectedLecture = LectureNum;
        
        c.ViewStudentListAndGrade(LectureNum, SetGradeTableModel);
        LecNum.setText(LectureNum);
        LectureInfo.setText((String) GradeTable.getValueAt(selectedRow, 1) + " 수강 학생 목록");
    }//GEN-LAST:event_SelectLectureGradeMouseClicked

    private void InputGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputGradeMouseClicked
        // TODO add your handling code here:
        InputGrade i = new InputGrade();
        CheckStudentList c = new CheckStudentList();
        String SNum = StudentNumField.getText();
        String Grade = (String) GradeComboBox.getSelectedItem();
        
        if ("".equals(SNum) || "".equals(Grade)) {
            JOptionPane.showInternalMessageDialog(null, "학생을 선택하세요.");
            return;
        }
        
        boolean inputGrade = i.InputGrade(SNum, Grade, LecNum.getText());
        if (inputGrade) {
            JOptionPane.showInternalMessageDialog(null, "성적 입력 완료");
        } else {
            JOptionPane.showInternalMessageDialog(null, "성적 입력 오류");
        }
        
        c.ViewStudentListAndGrade(LecNum.getText(), SetGradeTableModel);
        
        StudentNumField.setText("");
        StudentNameField.setText("");
        StudentMajorField.setText("");
    }//GEN-LAST:event_InputGradeMouseClicked

    private void VIEWLectureList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEWLectureList1MouseClicked
        // TODO add your handling code here:
        SETGRADE2panel.setVisible(false);
        SETGRADEPanel.setVisible(true);
        
        SETGRADE2panel.setEnabled(false);
        SETGRADEPanel.setEnabled(true);
    }//GEN-LAST:event_VIEWLectureList1MouseClicked

    private void LecTableToATDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LecTableToATDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LecTableToATDMouseClicked

    private void SelectLecture1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectLecture1MouseClicked
        // TODO add your handling code here:
        CheckStudentList c = new CheckStudentList();
        ATTENDANCEPanel.setVisible(true);
        ATTENDANCEPanel.setEnabled(true);
        
        VIEWATTENDANCEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setEnabled(false);
        
        int selectedRow = LecTableToATD.getSelectedRow();
        
        c.ViewStudentListAndGrade((String) LecTableToATD.getValueAt(selectedRow, 0), AttendanceTableModel);
        LecNumText.setText((String) LecTableToATD.getValueAt(selectedRow, 0));
        LecInfoText.setText((String) LecTableToATD.getValueAt(selectedRow, 1) + " 수강 학생 출석부");
    }//GEN-LAST:event_SelectLecture1MouseClicked

    private void AttendanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttendanceTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttendanceTableMouseClicked

    private void BackButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtMouseClicked
        // TODO add your handling code here:
        ATTENDANCEPanel.setVisible(false);
        ATTENDANCEPanel.setEnabled(false);
        
        VIEWATTENDANCEPanel.setVisible(true);
        VIEWATTENDANCEPanel.setEnabled(true);
    }//GEN-LAST:event_BackButtMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        boolean changeCheck = cp.changePassword(userID, NowPW.getText(), AfterPW.getText());
        
        if (changeCheck) {
            JOptionPane.showInternalMessageDialog(null, "변경 완료.");
        } else {
            JOptionPane.showInternalMessageDialog(null, "변경 오류.");
        }
        
        NowPW.setText("");
        AfterPW.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void ChangePWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseClicked
        // TODO add your handling code here:
        VIEWSTUDENTPanel.setVisible(false);
        SETGRADEPanel.setVisible(false);
        VIEWATTENDANCEPanel.setVisible(false);
        STUDENTLISTPanel.setVisible(false);
        SETGRADE2panel.setVisible(false);
        PASSWORDPanel.setVisible(true);
        
        VIEWSTUDENTPanel.setEnabled(false);
        SETGRADEPanel.setEnabled(false);
        VIEWATTENDANCEPanel.setEnabled(false);
        STUDENTLISTPanel.setEnabled(false);
        SETGRADE2panel.setEnabled(false);
        PASSWORDPanel.setEnabled(true);
    }//GEN-LAST:event_ChangePWMouseClicked

    private void ChangePWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseEntered
        // TODO add your handling code here:
        this.setCursor(HAND_CURSOR);
    }//GEN-LAST:event_ChangePWMouseEntered

    private void ChangePWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseExited
        // TODO add your handling code here:
        this.setCursor(0);
    }//GEN-LAST:event_ChangePWMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProfessorFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ATTENDANCEPanel;
    private javax.swing.JPasswordField AfterPW;
    private javax.swing.JTable AttendanceTable;
    private javax.swing.JButton BackButt;
    private javax.swing.JLabel BackGround;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JLabel ChagePasswordField;
    private javax.swing.JLabel ChangePW;
    private javax.swing.JLabel ChangePassword;
    private javax.swing.JLabel DragBar;
    private javax.swing.JLabel Exit;
    private javax.swing.JComboBox<String> GradeComboBox;
    private javax.swing.JTable GradeTable;
    private javax.swing.JLabel GradeText;
    private javax.swing.JButton InputGrade;
    private javax.swing.JLabel LecInfoText;
    private javax.swing.JLabel LecNum;
    private javax.swing.JLabel LecNumText;
    private javax.swing.JScrollPane LecTable1;
    private javax.swing.JTable LecTableToATD;
    private javax.swing.JLabel LectureInfo;
    private javax.swing.JTable LectureTable;
    private javax.swing.JLabel LogoutButt;
    private javax.swing.JLabel MajorBG;
    private javax.swing.JLabel MajorText;
    private javax.swing.JLabel NameBG;
    private javax.swing.JLabel NameText;
    private javax.swing.JTextField NowPW;
    private javax.swing.JLabel NowPasswordField;
    private javax.swing.JLabel NowPasswordText;
    private javax.swing.JLabel NowUser;
    private javax.swing.JPanel PASSWORDPanel;
    private javax.swing.JLabel SETGRADE;
    private javax.swing.JPanel SETGRADE2panel;
    private javax.swing.JPanel SETGRADEPanel;
    private javax.swing.JPanel STUDENTLISTPanel;
    private javax.swing.JLabel STUDENTLISTtext;
    private javax.swing.JButton SelectLecture;
    private javax.swing.JButton SelectLecture1;
    private javax.swing.JButton SelectLectureGrade;
    private javax.swing.JTable SetGradeTable;
    private javax.swing.JLabel SetGradeText;
    private javax.swing.JLabel SetGradeText2;
    private javax.swing.JTextField StudentMajorField;
    private javax.swing.JTextField StudentNameField;
    private javax.swing.JLabel StudentNumBG;
    private javax.swing.JTextField StudentNumField;
    private javax.swing.JLabel StudentNumText;
    private javax.swing.JTable StudentTable;
    private javax.swing.JLabel VIEWATTENDANCE;
    private javax.swing.JPanel VIEWATTENDANCEPanel;
    private javax.swing.JButton VIEWLectureList;
    private javax.swing.JButton VIEWLectureList1;
    private javax.swing.JLabel VIEWSTUDENT;
    private javax.swing.JPanel VIEWSTUDENTPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
