/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentJFrame;

import MainLoginJFrame.MainLoginFrame;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import Student.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DongHyeon Kim <20183188>
 */
public class StudentFrame extends javax.swing.JFrame {

    DefaultTableModel LectureTableModel;
    DefaultTableModel GradeTableModel;
    int mouseX;
    int mouseY;
    String userID = "";

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();

        LectureTableModel = (DefaultTableModel) LectureTable.getModel();
        GradeTableModel = (DefaultTableModel) GradeTable.getModel();

        RESISTLECTUREPanel.setVisible(true);
        CHECKGRADEPanel.setVisible(false);
        BILLPanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        RESISTLECTUREPanel.setEnabled(true);
        CHECKGRADEPanel.setEnabled(false);
        BILLPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(false);

        LectureNumField.setBackground(new Color(0, 0, 0, 1));
        LectureNameField.setBackground(new Color(0, 0, 0, 1));
        LectureMajorField.setBackground(new Color(0, 0, 0, 1));
        LectureCreditField.setBackground(new Color(0, 0, 0, 1));
        ProfessorField.setBackground(new Color(0, 0, 0, 1));
        NowPW.setBackground(new Color(0, 0, 0, 1));
        AfterPW.setBackground(new Color(0, 0, 0, 1));

        GradeFField.setBackground(new Color(0, 0, 0, 1));
        GradeField.setBackground(new Color(0, 0, 0, 1));

        ViewLectureList v = new ViewLectureList();
        v.ViewLectureList(LectureTableModel);
    }

    public StudentFrame(String userID) {
        initComponents();

        LectureTableModel = (DefaultTableModel) LectureTable.getModel();
        GradeTableModel = (DefaultTableModel) GradeTable.getModel();

        RESISTLECTUREPanel.setVisible(true);
        CHECKGRADEPanel.setVisible(false);
        BILLPanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        RESISTLECTUREPanel.setEnabled(true);
        CHECKGRADEPanel.setEnabled(false);
        BILLPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(false);

        LectureNumField.setBackground(new Color(0, 0, 0, 1));
        LectureNameField.setBackground(new Color(0, 0, 0, 1));
        LectureMajorField.setBackground(new Color(0, 0, 0, 1));
        LectureCreditField.setBackground(new Color(0, 0, 0, 1));
        ProfessorField.setBackground(new Color(0, 0, 0, 1));
        NowPW.setBackground(new Color(0, 0, 0, 1));
        AfterPW.setBackground(new Color(0, 0, 0, 1));
        
        GradeFField.setBackground(new Color(0, 0, 0, 1));
        GradeField.setBackground(new Color(0, 0, 0, 1));
        this.userID = userID;

        NowUserID.setText(userID);
        NowUserID.setForeground(Color.white);

        ViewLectureList v = new ViewLectureList();
        v.ViewLectureList(LectureTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RESISTLECTUREPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LectureTable = new javax.swing.JTable();
        RESISTButt = new javax.swing.JButton();
        ProfessorField = new javax.swing.JTextField();
        LectureCreditField = new javax.swing.JTextField();
        LectureMajorField = new javax.swing.JTextField();
        LectureNameField = new javax.swing.JTextField();
        LectureNumField = new javax.swing.JTextField();
        LectureNumBG = new javax.swing.JLabel();
        LectureNameBG = new javax.swing.JLabel();
        MajorBG = new javax.swing.JLabel();
        CreditBG = new javax.swing.JLabel();
        LectureNumText = new javax.swing.JLabel();
        LectureNameText = new javax.swing.JLabel();
        MajorText = new javax.swing.JLabel();
        CreditText = new javax.swing.JLabel();
        ProfessorBG = new javax.swing.JLabel();
        ProfessorText = new javax.swing.JLabel();
        LecOverlapCheck = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CHECKGRADEPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GradeTable = new javax.swing.JTable();
        GradeField = new javax.swing.JTextField();
        GradeFField = new javax.swing.JTextField();
        GradeFBG = new javax.swing.JLabel();
        GradeBG = new javax.swing.JLabel();
        GradeText = new javax.swing.JLabel();
        GradeFTExt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PASSWORDPanel = new javax.swing.JPanel();
        NowPW = new javax.swing.JTextField();
        AfterPW = new javax.swing.JPasswordField();
        ChangePassword = new javax.swing.JLabel();
        NowPasswordText = new javax.swing.JLabel();
        NowPasswordField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChagePasswordField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BILLPanel = new javax.swing.JPanel();
        SNUMFIELD = new javax.swing.JLabel();
        SNAMEFIELD = new javax.swing.JLabel();
        MAJORFIELD = new javax.swing.JLabel();
        CREDITFIELD = new javax.swing.JLabel();
        BILLFIELD = new javax.swing.JLabel();
        BILLTEXT = new javax.swing.JLabel();
        NameBG = new javax.swing.JLabel();
        MajorField = new javax.swing.JLabel();
        CreditFieldBG = new javax.swing.JLabel();
        PriceFieldBG = new javax.swing.JLabel();
        NameText = new javax.swing.JLabel();
        MajorLabel = new javax.swing.JLabel();
        NumFieldBG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pricetext = new javax.swing.JLabel();
        BasePanel = new javax.swing.JPanel();
        ChangePW = new javax.swing.JLabel();
        NowUserID = new javax.swing.JLabel();
        CHECKBILL = new javax.swing.JLabel();
        CHECKGRADE = new javax.swing.JLabel();
        RESISTLECTURE = new javax.swing.JLabel();
        LogoutButt = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        DragBar = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RESISTLECTUREPanel.setBackground(new java.awt.Color(250, 250, 250));
        RESISTLECTUREPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LectureTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LectureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "강의 번호", "강의명", "담당 학과", "학점", "담당 교수"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LectureTable.setRowHeight(25);
        LectureTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        LectureTable.setShowVerticalLines(false);
        LectureTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LectureTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LectureTable);

        RESISTLECTUREPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 590, 250));

        RESISTButt.setText("수강 신청");
        RESISTButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RESISTButtMouseClicked(evt);
            }
        });
        RESISTLECTUREPanel.add(RESISTButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 140, 40));

        ProfessorField.setEditable(false);
        ProfessorField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ProfessorField.setBorder(null);
        RESISTLECTUREPanel.add(ProfessorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 80, 30));

        LectureCreditField.setEditable(false);
        LectureCreditField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LectureCreditField.setBorder(null);
        RESISTLECTUREPanel.add(LectureCreditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 40, 30));

        LectureMajorField.setEditable(false);
        LectureMajorField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LectureMajorField.setBorder(null);
        RESISTLECTUREPanel.add(LectureMajorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 150, 30));

        LectureNameField.setEditable(false);
        LectureNameField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LectureNameField.setBorder(null);
        RESISTLECTUREPanel.add(LectureNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, 30));

        LectureNumField.setEditable(false);
        LectureNumField.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        LectureNumField.setBorder(null);
        RESISTLECTUREPanel.add(LectureNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 80, 30));

        LectureNumBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/MiddleInputField.png"))); // NOI18N
        RESISTLECTUREPanel.add(LectureNumBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 90, 30));

        LectureNameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        RESISTLECTUREPanel.add(LectureNameBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 160, 30));

        MajorBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        RESISTLECTUREPanel.add(MajorBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 160, 30));

        CreditBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/ShortInputField.png"))); // NOI18N
        RESISTLECTUREPanel.add(CreditBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 60, 30));

        LectureNumText.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        LectureNumText.setText("LectureNum");
        RESISTLECTUREPanel.add(LectureNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 90, -1));

        LectureNameText.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        LectureNameText.setText("LectureName");
        RESISTLECTUREPanel.add(LectureNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, -1));

        MajorText.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        MajorText.setText("Major");
        RESISTLECTUREPanel.add(MajorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 50, -1));

        CreditText.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        CreditText.setText("Credit");
        RESISTLECTUREPanel.add(CreditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 50, -1));

        ProfessorBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/MiddleInputField.png"))); // NOI18N
        RESISTLECTUREPanel.add(ProfessorBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 90, 30));

        ProfessorText.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        ProfessorText.setText("Professor");
        RESISTLECTUREPanel.add(ProfessorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));
        RESISTLECTUREPanel.add(LecOverlapCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 170, 20));

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel1.setText("RESIST LECTURE");
        RESISTLECTUREPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(RESISTLECTUREPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        CHECKGRADEPanel.setBackground(new java.awt.Color(250, 250, 250));
        CHECKGRADEPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GradeTable.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "강의 번호", "강의명", "성적"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GradeTable.setRowHeight(25);
        GradeTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        GradeTable.setShowVerticalLines(false);
        GradeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(GradeTable);

        CHECKGRADEPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 250));

        GradeField.setEditable(false);
        GradeField.setBorder(null);
        CHECKGRADEPanel.add(GradeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 80, 30));

        GradeFField.setEditable(false);
        GradeFField.setBorder(null);
        CHECKGRADEPanel.add(GradeFField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 80, 30));

        GradeFBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/MiddleInputField.png"))); // NOI18N
        CHECKGRADEPanel.add(GradeFBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 90, 30));

        GradeBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/MiddleInputField.png"))); // NOI18N
        CHECKGRADEPanel.add(GradeBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 90, 30));

        GradeText.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GradeText.setText("성적(F 미포함)");
        CHECKGRADEPanel.add(GradeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 80, 20));

        GradeFTExt.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        GradeFTExt.setText("성적(F 포함)");
        CHECKGRADEPanel.add(GradeFTExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 80, 20));

        jLabel2.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel2.setText("CHECK GRADE");
        CHECKGRADEPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(CHECKGRADEPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        PASSWORDPanel.setBackground(new java.awt.Color(250, 250, 250));
        PASSWORDPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NowPW.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        NowPW.setBorder(null);
        PASSWORDPanel.add(NowPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 150, 30));

        AfterPW.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        AfterPW.setBorder(null);
        PASSWORDPanel.add(AfterPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 30));

        ChangePassword.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        ChangePassword.setText("CHANGE PASSWORD");
        PASSWORDPanel.add(ChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 240, 50));

        NowPasswordText.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        NowPasswordText.setText("현재 비밀번호          :   ");
        PASSWORDPanel.add(NowPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        NowPasswordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        PASSWORDPanel.add(NowPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 30));

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel8.setText("변경할 비밀번호       : ");
        PASSWORDPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, -1));

        ChagePasswordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        PASSWORDPanel.add(ChagePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        jButton1.setText("비밀번호 변경");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PASSWORDPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 130, 40));

        getContentPane().add(PASSWORDPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        BILLPanel.setBackground(new java.awt.Color(250, 250, 250));
        BILLPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BILLPanel.add(SNUMFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 150, 30));
        BILLPanel.add(SNAMEFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 150, 30));
        BILLPanel.add(MAJORFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 150, 30));
        BILLPanel.add(CREDITFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 150, 30));
        BILLPanel.add(BILLFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 150, 30));

        BILLTEXT.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        BILLTEXT.setText("수강료 청구서");
        BILLPanel.add(BILLTEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        NameBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        BILLPanel.add(NameBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 160, 30));

        MajorField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        BILLPanel.add(MajorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 160, 30));

        CreditFieldBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        BILLPanel.add(CreditFieldBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 160, 30));

        PriceFieldBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        BILLPanel.add(PriceFieldBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 160, 30));

        NameText.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        NameText.setText("학생명        : ");
        BILLPanel.add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        MajorLabel.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        MajorLabel.setText("학과           :");
        BILLPanel.add(MajorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        NumFieldBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/InputField.png"))); // NOI18N
        BILLPanel.add(NumFieldBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, 30));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel3.setText("학번           :");
        BILLPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel4.setText("신청 학점    : ");
        BILLPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        Pricetext.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        Pricetext.setText("수강료        : ");
        BILLPanel.add(Pricetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        getContentPane().add(BILLPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        BasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangePW.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ChangePW.setForeground(new java.awt.Color(255, 255, 255));
        ChangePW.setText("비밀번호 변경");
        ChangePW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePWMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePWMouseExited(evt);
            }
        });
        BasePanel.add(ChangePW, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 20));
        BasePanel.add(NowUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 20));

        CHECKBILL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/CHECK BILL .png"))); // NOI18N
        CHECKBILL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHECKBILLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CHECKBILLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CHECKBILLMouseExited(evt);
            }
        });
        BasePanel.add(CHECKBILL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        CHECKGRADE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/CHECK GRADE .png"))); // NOI18N
        CHECKGRADE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CHECKGRADEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CHECKGRADEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CHECKGRADEMouseExited(evt);
            }
        });
        BasePanel.add(CHECKGRADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 50));

        RESISTLECTURE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/RESIST LECTURE.png"))); // NOI18N
        RESISTLECTURE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RESISTLECTUREMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RESISTLECTUREMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RESISTLECTUREMouseExited(evt);
            }
        });
        BasePanel.add(RESISTLECTURE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 50));

        LogoutButt.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        LogoutButt.setText(" LOGOUT");
        LogoutButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtMouseExited(evt);
            }
        });
        BasePanel.add(LogoutButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 60, 20));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/exitmini.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        BasePanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 30, 30));

        DragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragBarMouseDragged(evt);
            }
        });
        DragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragBarMousePressed(evt);
            }
        });
        BasePanel.add(DragBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/BaseBackGround.png"))); // NOI18N
        BasePanel.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        getContentPane().add(BasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_DragBarMouseDragged

    private void DragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragBarMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();

    }//GEN-LAST:event_DragBarMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_ExitMouseExited

    private void LogoutButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MainLoginFrame l = new MainLoginFrame();
        l.setVisible(true);
    }//GEN-LAST:event_LogoutButtMouseClicked

    private void LogoutButtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseEntered
        // TODO add your handling code here:
        this.setCursor(HAND_CURSOR);
    }//GEN-LAST:event_LogoutButtMouseEntered

    private void LogoutButtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseExited
        // TODO add your handling code here:
        this.setCursor(0);
    }//GEN-LAST:event_LogoutButtMouseExited

    private void RESISTLECTUREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESISTLECTUREMouseClicked
        // TODO add your handling code here:
        ViewLectureList v = new ViewLectureList();

        RESISTLECTUREPanel.setVisible(true);
        CHECKGRADEPanel.setVisible(false);
        BILLPanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        RESISTLECTUREPanel.setEnabled(true);
        CHECKGRADEPanel.setEnabled(false);
        BILLPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(false);

        v.ViewLectureList(LectureTableModel);
    }//GEN-LAST:event_RESISTLECTUREMouseClicked

    private void RESISTLECTUREMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESISTLECTUREMouseEntered
        // TODO add your handling code here:
        RESISTLECTURE.setIcon(new ImageIcon("./src/StudentJFrame/RESIST LECTURE Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_RESISTLECTUREMouseEntered

    private void RESISTLECTUREMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESISTLECTUREMouseExited
        // TODO add your handling code here:
        RESISTLECTURE.setIcon(new ImageIcon("./src/StudentJFrame/RESIST LECTURE.png"));
        this.setCursor(0);
    }//GEN-LAST:event_RESISTLECTUREMouseExited

    private void CHECKGRADEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKGRADEMouseClicked
        // TODO add your handling code here:
        CheckGrade c = new CheckGrade();
        RESISTLECTUREPanel.setVisible(false);
        CHECKGRADEPanel.setVisible(true);
        BILLPanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        RESISTLECTUREPanel.setEnabled(false);
        CHECKGRADEPanel.setEnabled(true);
        BILLPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(false);
        c.viewStudentGrade(userID, GradeTableModel, GradeFField, GradeField);
    }//GEN-LAST:event_CHECKGRADEMouseClicked

    private void CHECKGRADEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKGRADEMouseEntered
        // TODO add your handling code here:
        CHECKGRADE.setIcon(new ImageIcon("./src/StudentJFrame/CHECK GRADE Clicked .png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_CHECKGRADEMouseEntered

    private void CHECKGRADEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKGRADEMouseExited
        // TODO add your handling code here:
        CHECKGRADE.setIcon(new ImageIcon("./src/StudentJFrame/CHECK GRADE .png"));
        this.setCursor(0);
    }//GEN-LAST:event_CHECKGRADEMouseExited

    private void LectureTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LectureTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = LectureTable.getSelectedRow();
        String CourseNum = (String) LectureTable.getValueAt(selectedRow, 0);
        String CourseName = (String) LectureTable.getValueAt(selectedRow, 1);
        String Major = (String) LectureTable.getValueAt(selectedRow, 2);
        String Credit = (String) LectureTable.getValueAt(selectedRow, 3);
        String Professor = (String) LectureTable.getValueAt(selectedRow, 4);

        LectureNumField.setText(CourseNum);
        LectureNameField.setText(CourseName);
        LectureMajorField.setText(Major);
        LectureCreditField.setText(Credit);
        ProfessorField.setText(Professor);
    }//GEN-LAST:event_LectureTableMouseClicked

    private void RESISTButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RESISTButtMouseClicked
        // TODO add your handling code here:
        LecOverlapCheck.setText("");
        ResistLecture r = new ResistLecture();
        String LectureNum = LectureNumField.getText();
        String LectureName = LectureNameField.getText();

        if ("".equals(LectureNum) || "".equals(LectureName)) {
            JOptionPane.showInternalMessageDialog(null, "강의를 선택하세요.");
            return;
        }
        boolean ResistCheck = r.resistLecture(userID, LectureNum, LectureName, LecOverlapCheck);
        if (ResistCheck) {
            JOptionPane.showInternalMessageDialog(null, "수강 신청 완료");
            LecOverlapCheck.setText("");
            LectureNumField.setText("");
            LectureNameField.setText("");
            LectureMajorField.setText("");
            LectureCreditField.setText("");
            ProfessorField.setText("");
        } else {
            JOptionPane.showInternalMessageDialog(null, "수강 신청 오류");
        }


    }//GEN-LAST:event_RESISTButtMouseClicked

    private void GradeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradeTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeTableMouseClicked

    private void CHECKBILLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKBILLMouseClicked
        // TODO add your handling code here:
        RESISTLECTUREPanel.setVisible(false);
        CHECKGRADEPanel.setVisible(false);
        BILLPanel.setVisible(true);
        PASSWORDPanel.setVisible(false);

        RESISTLECTUREPanel.setEnabled(false);
        CHECKGRADEPanel.setEnabled(false);
        BILLPanel.setEnabled(true);
        PASSWORDPanel.setEnabled(false);
        CheckBill c = new CheckBill();
        c.CheckBill(userID, SNUMFIELD, SNAMEFIELD, MAJORFIELD, CREDITFIELD, BILLFIELD);
    }//GEN-LAST:event_CHECKBILLMouseClicked

    private void CHECKBILLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKBILLMouseEntered
        // TODO add your handling code here:
        CHECKBILL.setIcon(new ImageIcon("./src/StudentJFrame/CHECK BILL Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_CHECKBILLMouseEntered

    private void CHECKBILLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CHECKBILLMouseExited
        // TODO add your handling code here:
        CHECKBILL.setIcon(new ImageIcon("./src/StudentJFrame/CHECK BILL .png"));
        this.setCursor(0);
    }//GEN-LAST:event_CHECKBILLMouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        boolean changeCheck = cp.changePassword(userID, NowPW.getText(), AfterPW.getText());

        if (changeCheck) {
            JOptionPane.showInternalMessageDialog(null, "변경 완료.");
        } else {
            JOptionPane.showInternalMessageDialog(null, "변경 오류.");
        }

        NowPW.setText("");
        AfterPW.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void ChangePWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseClicked
        // TODO add your handling code here:
        RESISTLECTUREPanel.setVisible(false);
        CHECKGRADEPanel.setVisible(false);
        BILLPanel.setVisible(false);
        PASSWORDPanel.setVisible(true);

        RESISTLECTUREPanel.setEnabled(false);
        CHECKGRADEPanel.setEnabled(false);
        BILLPanel.setEnabled(false);
        PASSWORDPanel.setEnabled(true);
    }//GEN-LAST:event_ChangePWMouseClicked

    private void ChangePWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseEntered
        // TODO add your handling code here:
        this.setCursor(HAND_CURSOR);
    }//GEN-LAST:event_ChangePWMouseEntered

    private void ChangePWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseExited
        // TODO add your handling code here:
        this.setCursor(0);
    }//GEN-LAST:event_ChangePWMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField AfterPW;
    private javax.swing.JLabel BILLFIELD;
    private javax.swing.JPanel BILLPanel;
    private javax.swing.JLabel BILLTEXT;
    private javax.swing.JLabel BackGround;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JLabel CHECKBILL;
    private javax.swing.JLabel CHECKGRADE;
    private javax.swing.JPanel CHECKGRADEPanel;
    private javax.swing.JLabel CREDITFIELD;
    private javax.swing.JLabel ChagePasswordField;
    private javax.swing.JLabel ChangePW;
    private javax.swing.JLabel ChangePassword;
    private javax.swing.JLabel CreditBG;
    private javax.swing.JLabel CreditFieldBG;
    private javax.swing.JLabel CreditText;
    private javax.swing.JLabel DragBar;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel GradeBG;
    private javax.swing.JLabel GradeFBG;
    private javax.swing.JTextField GradeFField;
    private javax.swing.JLabel GradeFTExt;
    private javax.swing.JTextField GradeField;
    private javax.swing.JTable GradeTable;
    private javax.swing.JLabel GradeText;
    private javax.swing.JLabel LecOverlapCheck;
    private javax.swing.JTextField LectureCreditField;
    private javax.swing.JTextField LectureMajorField;
    private javax.swing.JLabel LectureNameBG;
    private javax.swing.JTextField LectureNameField;
    private javax.swing.JLabel LectureNameText;
    private javax.swing.JLabel LectureNumBG;
    private javax.swing.JTextField LectureNumField;
    private javax.swing.JLabel LectureNumText;
    private javax.swing.JTable LectureTable;
    private javax.swing.JLabel LogoutButt;
    private javax.swing.JLabel MAJORFIELD;
    private javax.swing.JLabel MajorBG;
    private javax.swing.JLabel MajorField;
    private javax.swing.JLabel MajorLabel;
    private javax.swing.JLabel MajorText;
    private javax.swing.JLabel NameBG;
    private javax.swing.JLabel NameText;
    private javax.swing.JTextField NowPW;
    private javax.swing.JLabel NowPasswordField;
    private javax.swing.JLabel NowPasswordText;
    private javax.swing.JLabel NowUserID;
    private javax.swing.JLabel NumFieldBG;
    private javax.swing.JPanel PASSWORDPanel;
    private javax.swing.JLabel PriceFieldBG;
    private javax.swing.JLabel Pricetext;
    private javax.swing.JLabel ProfessorBG;
    private javax.swing.JTextField ProfessorField;
    private javax.swing.JLabel ProfessorText;
    private javax.swing.JButton RESISTButt;
    private javax.swing.JLabel RESISTLECTURE;
    private javax.swing.JPanel RESISTLECTUREPanel;
    private javax.swing.JLabel SNAMEFIELD;
    private javax.swing.JLabel SNUMFIELD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
