/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainLoginJFrame;

import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import javax.swing.ImageIcon;
import LOGIN.Login;
import java.awt.Color;

/**
 *
 * @author DongHyeon Kim <20183188>
 */
public class MainLoginFrame extends javax.swing.JFrame {

    int mousePX;
    int mousePY;

    /**
     * Creates new form LoginFrame
     */
    public MainLoginFrame() {
        initComponents();
        InputID.setBackground(new Color(0, 0, 0, 1));
        InputPW.setBackground(new Color(0, 0, 0, 1));
        LoginStatusField.setBackground(new Color(0, 0, 0, 1));
        
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginStatusField = new javax.swing.JTextField();
        exit = new javax.swing.JLabel();
        MoveBar = new javax.swing.JLabel();
        InputID = new javax.swing.JTextField();
        InputPW = new javax.swing.JPasswordField();
        LoginButt = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginStatusField.setEditable(false);
        LoginStatusField.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        LoginStatusField.setBorder(null);
        LoginStatusField.setFocusable(false);
        jPanel1.add(LoginStatusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 230, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 30, 40));

        MoveBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoveBarMouseDragged(evt);
            }
        });
        MoveBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoveBarMousePressed(evt);
            }
        });
        jPanel1.add(MoveBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        InputID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        InputID.setForeground(new java.awt.Color(255, 255, 255));
        InputID.setBorder(null);
        InputID.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(InputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 230, 30));

        InputPW.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        InputPW.setForeground(new java.awt.Color(255, 255, 255));
        InputPW.setBorder(null);
        InputPW.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(InputPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 230, 40));

        LoginButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/LOGIN BUTT.png"))); // NOI18N
        LoginButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtMouseExited(evt);
            }
        });
        jPanel1.add(LoginButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 160, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginImage/JAVABackground.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtMouseEntered
        // TODO add your handling code here:
        LoginButt.setIcon(new ImageIcon("./src/LoginImage/CLICKED LOGIN.png"));
        LoginButt.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_LoginButtMouseEntered

    private void LoginButtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtMouseExited
        // TODO add your handling code here:
        LoginButt.setIcon(new ImageIcon("./src/LoginImage/LOGIN BUTT.png"));
    }//GEN-LAST:event_LoginButtMouseExited

    private void MoveBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousePX, y - mousePY);
    }//GEN-LAST:event_MoveBarMouseDragged

    private void MoveBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveBarMousePressed
        // TODO add your handling code here:
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_MoveBarMousePressed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void LoginButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtMouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setUserID(InputID.getText());
        l.setUserPassword(InputPW.getText());

        boolean LoginConfirm = l.LoginSystem();

        if (LoginConfirm)
            this.dispose();
        else {
            LoginStatusField.setText("WRONG ID or PASSWORD");
            LoginStatusField.setForeground(new Color(255, 0, 0));
        }
    }//GEN-LAST:event_LoginButtMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i += 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);

            try {
                Thread.sleep(50);
            } catch (InterruptedException e) {
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainLoginFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField InputID;
    private javax.swing.JPasswordField InputPW;
    private javax.swing.JLabel LoginButt;
    private javax.swing.JTextField LoginStatusField;
    private javax.swing.JLabel MoveBar;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
