/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CollegeManagerJFrame;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import CollegeManagement.*;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import MainLoginJFrame.MainLoginFrame;
import java.sql.SQLException;

/**
 *
 * @author DongHyeon Kim <20183188>
 */
public class CollegeManagerFrame extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
    DefaultTableModel model;
    DefaultTableModel ModifyTableModel;
    DefaultTableModel DeleteTableModel;
    String userID = "";

    /**
     * Creates new form StudentFrame
     */
    public CollegeManagerFrame() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        NumberField.setBackground(new Color(0, 0, 0, 1));
        NameField.setBackground(new Color(0, 0, 0, 1));
        SecurityField.setBackground(new Color(0, 0, 0, 1));
        SearchField.setBackground(new Color(0, 0, 0, 1));
        ModifyMajorCombo.setBackground(new Color(0, 0, 0, 0));
        ModifyNumField.setBackground(new Color(0, 0, 0, 1));
        ModifyNameField.setBackground(new Color(0, 0, 0, 1));

        SearchDelete.setBackground(new Color(0, 0, 0, 1));

        BasePanel.setVisible(true);
        BasePanel.setEnabled(true);

        AddPanel.setVisible(true);
        ViewPanel.setVisible(false);
        ModifyPanel.setVisible(false);
        DeletePanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        AddPanel.setEnabled(true);
        ViewPanel.setEnabled(false);
        ModifyPanel.setEnabled(false);
        DeletePanel.setEnabled(false);
        PASSWORDPanel.setVisible(false);

        model = (DefaultTableModel) InformTable.getModel();
        ModifyTableModel = (DefaultTableModel) ModifyinfoTable.getModel();
        DeleteTableModel = (DefaultTableModel) DeleteTable.getModel();

        NowPW.setBackground(new Color(0, 0, 0, 1));
        AfterPW.setBackground(new Color(0, 0, 0, 1));
        MajorCombo.setBackground(new Color(204, 204, 204, 0));
    }

    public CollegeManagerFrame(String userID) {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        NumberField.setBackground(new Color(0, 0, 0, 1));
        NameField.setBackground(new Color(0, 0, 0, 1));
        SecurityField.setBackground(new Color(0, 0, 0, 1));
        SearchField.setBackground(new Color(0, 0, 0, 1));
        ModifyMajorCombo.setBackground(new Color(0, 0, 0, 0));
        ModifyNumField.setBackground(new Color(0, 0, 0, 1));
        ModifyNameField.setBackground(new Color(0, 0, 0, 1));
        SearchDelete.setBackground(new Color(0, 0, 0, 1));

        BasePanel.setVisible(true);
        BasePanel.setEnabled(true);

        AddPanel.setVisible(true);
        ViewPanel.setVisible(false);
        ModifyPanel.setVisible(false);
        DeletePanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        AddPanel.setEnabled(true);
        ViewPanel.setEnabled(false);
        ModifyPanel.setEnabled(false);
        DeletePanel.setEnabled(false);
        PASSWORDPanel.setVisible(false);

        model = (DefaultTableModel) InformTable.getModel();
        ModifyTableModel = (DefaultTableModel) ModifyinfoTable.getModel();
        DeleteTableModel = (DefaultTableModel) DeleteTable.getModel();
        // model.insertRow(model.getRowCount(),new Object[]{"S001", "김동현", "111"});
        this.userID = userID;
        NowUserID.setText(userID);
        NowUserID.setForeground(Color.white);

        NowPW.setBackground(new Color(0, 0, 0, 1));
        AfterPW.setBackground(new Color(0, 0, 0, 1));
        MajorCombo.setBackground(new Color(204, 204, 204, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifyPanel = new javax.swing.JPanel();
        ModifyMajorCombo = new javax.swing.JComboBox<>();
        ModifyNumField = new javax.swing.JTextField();
        ModifyNameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ModifyinfoTable = new javax.swing.JTable();
        ModifyNumber = new javax.swing.JLabel();
        ModifyName = new javax.swing.JLabel();
        ModifyMajor = new javax.swing.JLabel();
        ModifyButton = new javax.swing.JButton();
        PeopleList = new javax.swing.JLabel();
        NumberStaticText = new javax.swing.JLabel();
        NameStaticText = new javax.swing.JLabel();
        MajorStaticText = new javax.swing.JLabel();
        MajorCheckLabel = new javax.swing.JLabel();
        AddPanel = new javax.swing.JPanel();
        NumberField = new javax.swing.JTextField();
        SecurityField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        MajorCombo = new javax.swing.JComboBox<>();
        ADDINFOText = new javax.swing.JLabel();
        InputBase = new javax.swing.JLabel();
        InputBase1 = new javax.swing.JLabel();
        InputBase2 = new javax.swing.JLabel();
        InputBase3 = new javax.swing.JLabel();
        NameText = new javax.swing.JLabel();
        MajorText = new javax.swing.JLabel();
        SecurityNumText = new javax.swing.JLabel();
        NumberText = new javax.swing.JLabel();
        ADDButt = new javax.swing.JButton();
        SecurityLabel = new javax.swing.JLabel();
        NumberLabel = new javax.swing.JLabel();
        MajorLabel = new javax.swing.JLabel();
        PASSWORDPanel = new javax.swing.JPanel();
        NowPW = new javax.swing.JTextField();
        AfterPW = new javax.swing.JPasswordField();
        ChangePassword = new javax.swing.JLabel();
        NowPasswordText = new javax.swing.JLabel();
        NowPasswordField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChagePasswordField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ViewPanel = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        inputBase = new javax.swing.JLabel();
        SearchButt = new javax.swing.JButton();
        SearchText = new javax.swing.JLabel();
        SearchStudent = new javax.swing.JRadioButton();
        SearchProfessor = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InformTable = new javax.swing.JTable();
        ViewInfoText = new javax.swing.JLabel();
        DeletePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DeleteTable = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        SearchDelete = new javax.swing.JTextField();
        StudentRadioButt = new javax.swing.JRadioButton();
        ProfessorRadioButt = new javax.swing.JRadioButton();
        inputBackground = new javax.swing.JLabel();
        SearchDeleteButt = new javax.swing.JButton();
        ViewList = new javax.swing.JButton();
        DeleteInfoText = new javax.swing.JLabel();
        BasePanel = new javax.swing.JPanel();
        ChangePW = new javax.swing.JLabel();
        LogoutButt = new javax.swing.JLabel();
        NowUserID = new javax.swing.JLabel();
        DELETE_INFO = new javax.swing.JLabel();
        MODIFY_INFO = new javax.swing.JLabel();
        VIEW_INFO = new javax.swing.JLabel();
        ADD_INFO = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        DragBar = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModifyPanel.setBackground(new java.awt.Color(250, 250, 250));
        ModifyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModifyMajorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전산학과", "전자공학과", "화학공학과", "기계공학과", "항공우주공학과" }));
        ModifyPanel.add(ModifyMajorCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 150, 40));

        ModifyNumField.setEditable(false);
        ModifyNumField.setBorder(null);
        ModifyPanel.add(ModifyNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 40));

        ModifyNameField.setBorder(null);
        ModifyPanel.add(ModifyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 150, 40));

        ModifyinfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Number", "Name", "Major"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ModifyinfoTable.setFocusable(false);
        ModifyinfoTable.setRowHeight(25);
        ModifyinfoTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        ModifyinfoTable.setShowVerticalLines(false);
        ModifyinfoTable.getTableHeader().setReorderingAllowed(false);
        ModifyinfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyinfoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ModifyinfoTable);

        ModifyPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 550, 250));

        ModifyNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        ModifyPanel.add(ModifyNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 160, 40));

        ModifyName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        ModifyPanel.add(ModifyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 160, 40));

        ModifyMajor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        ModifyPanel.add(ModifyMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 160, 40));

        ModifyButton.setText("수정");
        ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyButtonMouseClicked(evt);
            }
        });
        ModifyPanel.add(ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 140, 40));

        PeopleList.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        PeopleList.setText("MODIFY INFO");
        ModifyPanel.add(PeopleList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 40));

        NumberStaticText.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        NumberStaticText.setText("Number");
        ModifyPanel.add(NumberStaticText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        NameStaticText.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        NameStaticText.setText("Name");
        ModifyPanel.add(NameStaticText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        MajorStaticText.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        MajorStaticText.setText("Major");
        ModifyPanel.add(MajorStaticText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        MajorCheckLabel.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ModifyPanel.add(MajorCheckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 220, 20));

        getContentPane().add(ModifyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        AddPanel.setBackground(new java.awt.Color(250, 250, 250));
        AddPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumberField.setBorder(null);
        NumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberFieldActionPerformed(evt);
            }
        });
        AddPanel.add(NumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, 40));

        SecurityField.setBorder(null);
        AddPanel.add(SecurityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 150, 40));

        NameField.setBorder(null);
        AddPanel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 150, 40));

        MajorCombo.setBackground(new java.awt.Color(204, 204, 204));
        MajorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전산학과", "전자공학과", "화학공학과", "기계공학과", "항공우주공학과" }));
        MajorCombo.setBorder(null);
        AddPanel.add(MajorCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 40));

        ADDINFOText.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        ADDINFOText.setText("ADD INFO");
        AddPanel.add(ADDINFOText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        InputBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        AddPanel.add(InputBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, 40));

        InputBase1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        AddPanel.add(InputBase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, 40));

        InputBase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        AddPanel.add(InputBase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 160, 40));

        InputBase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        AddPanel.add(InputBase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 160, 40));

        NameText.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        NameText.setText("Name");
        AddPanel.add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        MajorText.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        MajorText.setText("Major");
        AddPanel.add(MajorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        SecurityNumText.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        SecurityNumText.setText("SecurityNumber");
        AddPanel.add(SecurityNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        NumberText.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        NumberText.setText("Number");
        AddPanel.add(NumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        ADDButt.setText("ADD INFO");
        ADDButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDButtMouseClicked(evt);
            }
        });
        AddPanel.add(ADDButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 130, 40));
        AddPanel.add(SecurityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 260, 20));
        AddPanel.add(NumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 260, 20));
        AddPanel.add(MajorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 240, 20));

        getContentPane().add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        PASSWORDPanel.setBackground(new java.awt.Color(250, 250, 250));
        PASSWORDPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NowPW.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        NowPW.setBorder(null);
        PASSWORDPanel.add(NowPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 150, 30));

        AfterPW.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        AfterPW.setBorder(null);
        PASSWORDPanel.add(AfterPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 30));

        ChangePassword.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        ChangePassword.setText("CHANGE PASSWORD");
        PASSWORDPanel.add(ChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 240, 50));

        NowPasswordText.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        NowPasswordText.setText("현재 비밀번호          :   ");
        PASSWORDPanel.add(NowPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        NowPasswordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        PASSWORDPanel.add(NowPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 30));

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel8.setText("변경할 비밀번호       : ");
        PASSWORDPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, -1));

        ChagePasswordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfessorJFrame/InputField.png"))); // NOI18N
        PASSWORDPanel.add(ChagePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        jButton1.setText("비밀번호 변경");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PASSWORDPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 130, 40));

        getContentPane().add(PASSWORDPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        ViewPanel.setBackground(new java.awt.Color(250, 250, 250));
        ViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchField.setBorder(null);
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });
        ViewPanel.add(SearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 150, 40));

        inputBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        ViewPanel.add(inputBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 160, 40));

        SearchButt.setText("Search");
        SearchButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtMouseClicked(evt);
            }
        });
        ViewPanel.add(SearchButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 130, 40));

        SearchText.setFont(new java.awt.Font("Source Code Pro", 0, 14)); // NOI18N
        SearchText.setText("Search Name or Number");
        ViewPanel.add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 170, 20));

        SearchStudent.setBackground(new java.awt.Color(250, 250, 250));
        SearchStudent.setText("Student");
        SearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentActionPerformed(evt);
            }
        });
        ViewPanel.add(SearchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        SearchProfessor.setBackground(new java.awt.Color(250, 250, 250));
        SearchProfessor.setText("Professor");
        SearchProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProfessorActionPerformed(evt);
            }
        });
        ViewPanel.add(SearchProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        InformTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Number", "Name", "Major"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InformTable.setFocusable(false);
        InformTable.setRowHeight(25);
        InformTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        InformTable.setShowVerticalLines(false);
        InformTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(InformTable);

        ViewPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 550, 250));

        ViewInfoText.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        ViewInfoText.setText("VIEW & SEARCH INFO");
        ViewPanel.add(ViewInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(ViewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        DeletePanel.setBackground(new java.awt.Color(250, 250, 250));
        DeletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Number", "Name", "Major"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DeleteTable.setFocusable(false);
        DeleteTable.setRowHeight(25);
        DeleteTable.setSelectionBackground(new java.awt.Color(0, 204, 255));
        DeleteTable.setShowVerticalLines(false);
        DeleteTable.getTableHeader().setReorderingAllowed(false);
        DeleteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(DeleteTable);

        DeletePanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 560, 250));

        DeleteButton.setText("삭제");
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });
        DeletePanel.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 160, 40));

        SearchDelete.setBorder(null);
        DeletePanel.add(SearchDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, 40));

        StudentRadioButt.setBackground(new java.awt.Color(250, 250, 250));
        StudentRadioButt.setText("Student");
        StudentRadioButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentRadioButtActionPerformed(evt);
            }
        });
        DeletePanel.add(StudentRadioButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        ProfessorRadioButt.setBackground(new java.awt.Color(250, 250, 250));
        ProfessorRadioButt.setText("Professor");
        ProfessorRadioButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorRadioButtActionPerformed(evt);
            }
        });
        DeletePanel.add(ProfessorRadioButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        inputBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/InputField.png"))); // NOI18N
        DeletePanel.add(inputBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, 40));

        SearchDeleteButt.setText("검색");
        SearchDeleteButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchDeleteButtMouseClicked(evt);
            }
        });
        DeletePanel.add(SearchDeleteButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 160, 40));

        ViewList.setText("전체 목록 출력");
        ViewList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewListMouseClicked(evt);
            }
        });
        DeletePanel.add(ViewList, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 150, 40));

        DeleteInfoText.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        DeleteInfoText.setText("DELETE INFO");
        DeletePanel.add(DeleteInfoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 40));

        getContentPane().add(DeletePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 670, 470));

        BasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChangePW.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        ChangePW.setForeground(new java.awt.Color(255, 255, 255));
        ChangePW.setText("비밀번호 변경");
        ChangePW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePWMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePWMouseExited(evt);
            }
        });
        BasePanel.add(ChangePW, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 20));

        LogoutButt.setFont(new java.awt.Font("Source Code Pro", 0, 12)); // NOI18N
        LogoutButt.setText(" LOGOUT");
        LogoutButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtMouseExited(evt);
            }
        });
        BasePanel.add(LogoutButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 60, 20));
        BasePanel.add(NowUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 120, 20));

        DELETE_INFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/DELETE INFO.png"))); // NOI18N
        DELETE_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETE_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DELETE_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DELETE_INFOMouseExited(evt);
            }
        });
        BasePanel.add(DELETE_INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, 50));

        MODIFY_INFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/MODIFY INFO.png"))); // NOI18N
        MODIFY_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MODIFY_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MODIFY_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MODIFY_INFOMouseExited(evt);
            }
        });
        BasePanel.add(MODIFY_INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 50));

        VIEW_INFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/VIEW INFO.png"))); // NOI18N
        VIEW_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VIEW_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VIEW_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VIEW_INFOMouseExited(evt);
            }
        });
        BasePanel.add(VIEW_INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 50));

        ADD_INFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/ADD INFO.png"))); // NOI18N
        ADD_INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD_INFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD_INFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADD_INFOMouseExited(evt);
            }
        });
        BasePanel.add(ADD_INFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 50));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CollegeManagerJFrame/exitmini.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        BasePanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 30, 30));

        DragBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragBarMouseDragged(evt);
            }
        });
        DragBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragBarMousePressed(evt);
            }
        });
        BasePanel.add(DragBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentJFrame/BaseBackGround.png"))); // NOI18N
        BasePanel.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        getContentPane().add(BasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DragBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_DragBarMouseDragged

    private void DragBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragBarMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();

    }//GEN-LAST:event_DragBarMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_ExitMouseEntered

    private void ADD_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_INFOMouseEntered
        // TODO add your handling code here:
        ADD_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/ADD INFO Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_ADD_INFOMouseEntered

    private void ADD_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_INFOMouseExited
        // TODO add your handling code here:
        ADD_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/ADD INFO.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_ADD_INFOMouseExited

    private void VIEW_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEW_INFOMouseEntered
        // TODO add your handling code here:
        VIEW_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/VIEW INFO Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_VIEW_INFOMouseEntered

    private void VIEW_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEW_INFOMouseExited
        // TODO add your handling code here:
        VIEW_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/VIEW INFO.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_VIEW_INFOMouseExited

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        // TODO add your handling code here:
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_ExitMouseExited

    private void MODIFY_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MODIFY_INFOMouseEntered
        // TODO add your handling code here:
        MODIFY_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/MODIFY INFO Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_MODIFY_INFOMouseEntered

    private void MODIFY_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MODIFY_INFOMouseExited
        // TODO add your handling code here:
        MODIFY_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/MODIFY INFO.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_MODIFY_INFOMouseExited

    private void DELETE_INFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETE_INFOMouseEntered
        // TODO add your handling code here:
        DELETE_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/DELETE INFO Clicked.png"));
        this.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_DELETE_INFOMouseEntered

    private void DELETE_INFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETE_INFOMouseExited
        // TODO add your handling code here:
        DELETE_INFO.setIcon(new ImageIcon("./src/CollegeManagerJFrame/DELETE INFO.png"));
        this.setCursor(new Cursor(0));
    }//GEN-LAST:event_DELETE_INFOMouseExited

    private void NumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberFieldActionPerformed

    private void ADDButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDButtMouseClicked
        // TODO add your handling code here:
        NumberLabel.setText("");
        SecurityLabel.setText("");

        AddInfo ad = new AddInfo();
        String Number = NumberField.getText();
        String Name = NameField.getText();
        String Major = (String) MajorCombo.getSelectedItem();//MajorField.getText();
        String SecurityNum = SecurityField.getText();
        boolean AddCheck = ad.AddInfo(Name, Major, SecurityNum, Number, NumberLabel, SecurityLabel, MajorLabel);

        if (AddCheck) {
            JOptionPane.showInternalMessageDialog(null, "정보 등록 완료");

            NumberField.setText("");
            NameField.setText("");
            SecurityField.setText("");
            NumberLabel.setText("");
            SecurityLabel.setText("");
        } else {
            JOptionPane.showInternalMessageDialog(null, "정보 등록 오류");
        }

    }//GEN-LAST:event_ADDButtMouseClicked

    private void ADD_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD_INFOMouseClicked
        // TODO add your handling code here:

        AddPanel.setVisible(true);
        ViewPanel.setVisible(false);
        ModifyPanel.setVisible(false);
        DeletePanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        AddPanel.setEnabled(true);
        ViewPanel.setEnabled(false);
        ModifyPanel.setEnabled(false);
        DeletePanel.setEnabled(false);
        PASSWORDPanel.setVisible(false);

        NumberField.setText("");
        NameField.setText("");
        SecurityField.setText("");
        NumberLabel.setText("");
        SecurityLabel.setText("");
    }//GEN-LAST:event_ADD_INFOMouseClicked

    private void VIEW_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VIEW_INFOMouseClicked
        // TODO add your handling code here:
        AddPanel.setVisible(false);
        ViewPanel.setVisible(true);
        ModifyPanel.setVisible(false);
        DeletePanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        AddPanel.setEnabled(false);
        ViewPanel.setEnabled(true);
        ModifyPanel.setEnabled(false);
        DeletePanel.setEnabled(false);
        PASSWORDPanel.setVisible(false);
        ViewAllStudentorProfessor(model);

    }//GEN-LAST:event_VIEW_INFOMouseClicked
    private void ViewAllStudentorProfessor(DefaultTableModel JTable) {

        try {

            CollegeManager cm = new CollegeManager();
            cm.ViewStudent();

            ResultSet rs = cm.ViewStudent();
            JTable.setRowCount(0);

            while (rs.next()) {
                String SNum = rs.getString("NUMBER");
                String SName = rs.getString("NAME");
                String SMajor = rs.getString("MAJOR");

                JTable.insertRow(JTable.getRowCount(), new Object[]{SNum, SName, SMajor});
            }

            rs = cm.ViewProfessor();
            while (rs.next()) {
                String PNum = rs.getString("NUMBER");
                String PName = rs.getString("NAME");
                String PMajor = rs.getString("MAJOR");

                JTable.insertRow(JTable.getRowCount(), new Object[]{PNum, PName, PMajor});
            }
        } catch (SQLException e) {
            JOptionPane.showInternalMessageDialog(null, "학생 출력 오류");
        }
    }
    private void MODIFY_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MODIFY_INFOMouseClicked
        // TODO add your handling code here:
        AddPanel.setVisible(false);
        ViewPanel.setVisible(false);
        ModifyPanel.setVisible(true);
        DeletePanel.setVisible(false);
        PASSWORDPanel.setVisible(false);

        AddPanel.setEnabled(false);
        ViewPanel.setEnabled(false);
        ModifyPanel.setEnabled(true);
        DeletePanel.setEnabled(false);
        PASSWORDPanel.setVisible(false);
        ViewAllStudentorProfessor(ModifyTableModel);
    }//GEN-LAST:event_MODIFY_INFOMouseClicked

    private void DELETE_INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETE_INFOMouseClicked
        // TODO add your handling code here:
        AddPanel.setVisible(false);
        ViewPanel.setVisible(false);
        ModifyPanel.setVisible(false);
        DeletePanel.setVisible(true);
        PASSWORDPanel.setVisible(false);

        AddPanel.setEnabled(false);
        ViewPanel.setEnabled(false);
        ModifyPanel.setEnabled(false);
        DeletePanel.setEnabled(true);
        PASSWORDPanel.setVisible(false);

        ViewAllStudentorProfessor(DeleteTableModel);
    }//GEN-LAST:event_DELETE_INFOMouseClicked

    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFieldActionPerformed

    private void SearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentActionPerformed
        // TODO add your handling code here:
        if (SearchStudent.isSelected()) {
            SearchProfessor.setSelected(false);
        }
    }//GEN-LAST:event_SearchStudentActionPerformed

    private void SearchProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProfessorActionPerformed
        // TODO add your handling code here:
        if (SearchProfessor.isSelected()) {
            SearchStudent.setSelected(false);
        }
    }//GEN-LAST:event_SearchProfessorActionPerformed

    private void SearchButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtMouseClicked
        // TODO add your handling code here:

        SearchInfo s = new SearchInfo();
        String target = SearchField.getText();
        ResultSet rs = null;
        if (!SearchStudent.isSelected() && !SearchProfessor.isSelected()) {
            JOptionPane.showInternalMessageDialog(null, "PLEASE SELECT STUDENT OR PROFESSOR");
            return;
        }
        try {
            model.setRowCount(0);
            if (target.matches("^[SP]\\d{3}$") || target.matches("^[가-힣]*$")) {
                if (SearchStudent.isSelected()) {
                    rs = s.StudentSearch(target);
                } else {
                    rs = s.ProffesorSearch(target);
                }
            }

            while (rs.next()) {
                String name = rs.getString("NAME");
                String number = rs.getString("NUMBER");
                String major = rs.getString("MAJOR");
                model.insertRow(model.getRowCount(), new Object[]{number, name, major});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR !");
        }
    }//GEN-LAST:event_SearchButtMouseClicked

    private void ModifyinfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyinfoTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = ModifyinfoTable.getSelectedRow();
        String Number = (String) ModifyinfoTable.getValueAt(selectedRow, 0);
        String Name = (String) ModifyinfoTable.getValueAt(selectedRow, 1);
        String Major = (String) ModifyinfoTable.getValueAt(selectedRow, 2);

        ModifyNumField.setText(Number);
        ModifyNameField.setText(Name);

    }//GEN-LAST:event_ModifyinfoTableMouseClicked

    private void ModifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyButtonMouseClicked
        // TODO add your handling code here:
        String selectNum = ModifyNumField.getText();
        String changeName = ModifyNameField.getText();
        String changeMajor = (String) ModifyMajorCombo.getSelectedItem();// ModifyMajorField.getText();

        ModifyInfo m = new ModifyInfo();
        boolean UpdateCheck = m.ModifyInfo(selectNum, changeName, changeMajor, MajorCheckLabel);

        if (!UpdateCheck) {
            JOptionPane.showInternalMessageDialog(null, "수정 실패");
        } else {
            JOptionPane.showInternalMessageDialog(null, "수정 완료");
        }
        ViewAllStudentorProfessor(ModifyTableModel);

        ModifyNumField.setText("");
        ModifyNameField.setText("");
        MajorCheckLabel.setText("");
    }//GEN-LAST:event_ModifyButtonMouseClicked

    private void DeleteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteTableMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_DeleteTableMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        // TODO add your handling code here:
        int selectedRow = DeleteTable.getSelectedRow();
        String selectedNum = (String) DeleteTable.getValueAt(selectedRow, 0);
        String selectedName = (String) DeleteTable.getValueAt(selectedRow, 1);

        //JOptionPane.showInternalMessageDialog(null, selectedNum + selectedName);
        DeleteInfo d = new DeleteInfo();
        boolean DeleteCheck = d.DeleteInfo(selectedNum, selectedName);

        if (!DeleteCheck) {
            JOptionPane.showInternalMessageDialog(null, "삭제 오류");
        } else {
            JOptionPane.showInternalMessageDialog(null, "삭제 성공");
        }
        ViewAllStudentorProfessor(DeleteTableModel);
        SearchDelete.setText("");
    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void StudentRadioButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentRadioButtActionPerformed
        // TODO add your handling code here:
        if (StudentRadioButt.isSelected()) {
            ProfessorRadioButt.setSelected(false);
        }
    }//GEN-LAST:event_StudentRadioButtActionPerformed

    private void ProfessorRadioButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorRadioButtActionPerformed
        // TODO add your handling code here:
        if (ProfessorRadioButt.isSelected()) {
            StudentRadioButt.setSelected(false);
        }
    }//GEN-LAST:event_ProfessorRadioButtActionPerformed

    private void SearchDeleteButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchDeleteButtMouseClicked
        // TODO add your handling code here:
        SearchInfo s = new SearchInfo();
        String target = SearchDelete.getText();

        if (!StudentRadioButt.isSelected() && !ProfessorRadioButt.isSelected()) {
            JOptionPane.showInternalMessageDialog(null, "학생과 교수 중 하나를 선택해주세요");
            return;
        }
        s.Search(target, StudentRadioButt.isSelected(), DeleteTableModel);
    }//GEN-LAST:event_SearchDeleteButtMouseClicked

    private void ViewListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewListMouseClicked
        // TODO add your handling code here:
        ViewAllStudentorProfessor(DeleteTableModel);
        SearchDelete.setText("");
    }//GEN-LAST:event_ViewListMouseClicked

    private void LogoutButtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseEntered
        // TODO add your handling code here:
        this.setCursor(HAND_CURSOR);
    }//GEN-LAST:event_LogoutButtMouseEntered

    private void LogoutButtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseExited
        // TODO add your handling code here:
        this.setCursor(0);
    }//GEN-LAST:event_LogoutButtMouseExited

    private void LogoutButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MainLoginFrame l = new MainLoginFrame();
        l.setVisible(true);
    }//GEN-LAST:event_LogoutButtMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();
        boolean changeCheck = cp.changePassword(userID, NowPW.getText(), AfterPW.getText());

        if (changeCheck) {
            JOptionPane.showInternalMessageDialog(null, "변경 완료.");
        } else {
            JOptionPane.showInternalMessageDialog(null, "변경 오류.");
        }

        NowPW.setText("");
        AfterPW.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void ChangePWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseClicked
        // TODO add your handling code here:
        AddPanel.setVisible(false);
        ViewPanel.setVisible(false);
        ModifyPanel.setVisible(false);
        DeletePanel.setVisible(false);
        PASSWORDPanel.setVisible(true);

        AddPanel.setEnabled(false);
        ViewPanel.setEnabled(false);
        ModifyPanel.setEnabled(false);
        DeletePanel.setEnabled(false);
        PASSWORDPanel.setVisible(true);
    }//GEN-LAST:event_ChangePWMouseClicked

    private void ChangePWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseEntered
        // TODO add your handling code here:
        this.setCursor(HAND_CURSOR);
    }//GEN-LAST:event_ChangePWMouseEntered

    private void ChangePWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePWMouseExited
        // TODO add your handling code here:
        this.setCursor(0);
    }//GEN-LAST:event_ChangePWMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollegeManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CollegeManagerFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDButt;
    private javax.swing.JLabel ADDINFOText;
    private javax.swing.JLabel ADD_INFO;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JPasswordField AfterPW;
    private javax.swing.JLabel BackGround;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JLabel ChagePasswordField;
    private javax.swing.JLabel ChangePW;
    private javax.swing.JLabel ChangePassword;
    private javax.swing.JLabel DELETE_INFO;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DeleteInfoText;
    private javax.swing.JPanel DeletePanel;
    private javax.swing.JTable DeleteTable;
    private javax.swing.JLabel DragBar;
    private javax.swing.JLabel Exit;
    private javax.swing.JTable InformTable;
    private javax.swing.JLabel InputBase;
    private javax.swing.JLabel InputBase1;
    private javax.swing.JLabel InputBase2;
    private javax.swing.JLabel InputBase3;
    private javax.swing.JLabel LogoutButt;
    private javax.swing.JLabel MODIFY_INFO;
    private javax.swing.JLabel MajorCheckLabel;
    private javax.swing.JComboBox<String> MajorCombo;
    private javax.swing.JLabel MajorLabel;
    private javax.swing.JLabel MajorStaticText;
    private javax.swing.JLabel MajorText;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel ModifyMajor;
    private javax.swing.JComboBox<String> ModifyMajorCombo;
    private javax.swing.JLabel ModifyName;
    private javax.swing.JTextField ModifyNameField;
    private javax.swing.JTextField ModifyNumField;
    private javax.swing.JLabel ModifyNumber;
    private javax.swing.JPanel ModifyPanel;
    private javax.swing.JTable ModifyinfoTable;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameStaticText;
    private javax.swing.JLabel NameText;
    private javax.swing.JTextField NowPW;
    private javax.swing.JLabel NowPasswordField;
    private javax.swing.JLabel NowPasswordText;
    private javax.swing.JLabel NowUserID;
    private javax.swing.JTextField NumberField;
    private javax.swing.JLabel NumberLabel;
    private javax.swing.JLabel NumberStaticText;
    private javax.swing.JLabel NumberText;
    private javax.swing.JPanel PASSWORDPanel;
    private javax.swing.JLabel PeopleList;
    private javax.swing.JRadioButton ProfessorRadioButt;
    private javax.swing.JButton SearchButt;
    private javax.swing.JTextField SearchDelete;
    private javax.swing.JButton SearchDeleteButt;
    private javax.swing.JTextField SearchField;
    private javax.swing.JRadioButton SearchProfessor;
    private javax.swing.JRadioButton SearchStudent;
    private javax.swing.JLabel SearchText;
    private javax.swing.JTextField SecurityField;
    private javax.swing.JLabel SecurityLabel;
    private javax.swing.JLabel SecurityNumText;
    private javax.swing.JRadioButton StudentRadioButt;
    private javax.swing.JLabel VIEW_INFO;
    private javax.swing.JLabel ViewInfoText;
    private javax.swing.JButton ViewList;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JLabel inputBackground;
    private javax.swing.JLabel inputBase;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
